<?php

namespace ContainerPCPNs5A;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AOfqXWMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AOfqXWM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AOfqXWM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'joinMatchHandler' => ['privates', 'App\\FormHandler\\JoinMatchHandler', 'getJoinMatchHandlerService', true],
            'match' => ['privates', '.errored..service_locator.AOfqXWM.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.AOfqXWM": it needs an instance of "App\\Entity\\Event" but this type has been excluded in "config/services.yaml".'],
        ], [
            'joinMatchHandler' => 'App\\FormHandler\\JoinMatchHandler',
            'match' => 'App\\Entity\\Event',
        ]);
    }
}
