<?php

namespace ContainerD1nOpgo;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z_MvfQAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z.mvfQA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z.mvfQA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'matchFormHandler' => ['privates', 'App\\FormHandler\\MatchFormHandler', 'getMatchFormHandlerService', true],
            'user' => ['privates', '.errored..service_locator.z.mvfQA.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.z.mvfQA": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'matchFormHandler' => 'App\\FormHandler\\MatchFormHandler',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
