<?php

namespace ContainerBCPtx0w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TyX2YZJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tyX2YZJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tyX2YZJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'matchFormHandler' => ['privates', 'App\\FormHandler\\MatchFormHandler', 'getMatchFormHandlerService', true],
        ], [
            'matchFormHandler' => 'App\\FormHandler\\MatchFormHandler',
        ]);
    }
}
